#nullable enable

namespace Microscope.CodeAnalysis {
    using System.Text.RegularExpressions;

    public static class Documentation {
        public static string? For(string opCode) =>
            GetRaw(opCode)?
            .RegexReplace("<paramref name=\"([^\"]+)\" />", m => $"`{m.Groups[1].Value}`")
            .RegexReplace("<see cref=\"T:([^\"]+)\" />",    m => $"`{m.Groups[1].Value}`");

        // Generated with ./src/CodeLensProvider/gen-opcode-doc-switch-cases.linq
        // Yes, this is hard-coded. But to me this solution seems way less brittle than dynamically
        // locating 'System.Reflection.Primitives.xml' on the user's system and feeding it into a
        // library that parses the documentation (e.g. LoxSmoke.DocXml).
        private static string? GetRaw(string opCode) => opCode switch {
            "add"            => "Adds two values and pushes the result onto the evaluation stack.",
            "add.ovf"        => "Adds two integers, performs an overflow check, and pushes the result onto the evaluation stack.",
            "add.ovf.un"     => "Adds two unsigned integer values, performs an overflow check, and pushes the result onto the evaluation stack.",
            "and"            => "Computes the bitwise AND of two values and pushes the result onto the evaluation stack.",
            "arglist"        => "Returns an unmanaged pointer to the argument list of the current method.",
            "beq"            => "Transfers control to a target instruction if two values are equal.",
            "beq.s"          => "Transfers control to a target instruction (short form) if two values are equal.",
            "bge"            => "Transfers control to a target instruction if the first value is greater than or equal to the second value.",
            "bge.s"          => "Transfers control to a target instruction (short form) if the first value is greater than or equal to the second value.",
            "bge.un"         => "Transfers control to a target instruction if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.",
            "bge.un.s"       => "Transfers control to a target instruction (short form) if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.",
            "bgt"            => "Transfers control to a target instruction if the first value is greater than the second value.",
            "bgt.s"          => "Transfers control to a target instruction (short form) if the first value is greater than the second value.",
            "bgt.un"         => "Transfers control to a target instruction if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.",
            "bgt.un.s"       => "Transfers control to a target instruction (short form) if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.",
            "ble"            => "Transfers control to a target instruction if the first value is less than or equal to the second value.",
            "ble.s"          => "Transfers control to a target instruction (short form) if the first value is less than or equal to the second value.",
            "ble.un"         => "Transfers control to a target instruction if the first value is less than or equal to the second value, when comparing unsigned integer values or unordered float values.",
            "ble.un.s"       => "Transfers control to a target instruction (short form) if the first value is less than or equal to the second value, when comparing unsigned integer values or unordered float values.",
            "blt"            => "Transfers control to a target instruction if the first value is less than the second value.",
            "blt.s"          => "Transfers control to a target instruction (short form) if the first value is less than the second value.",
            "blt.un"         => "Transfers control to a target instruction if the first value is less than the second value, when comparing unsigned integer values or unordered float values.",
            "blt.un.s"       => "Transfers control to a target instruction (short form) if the first value is less than the second value, when comparing unsigned integer values or unordered float values.",
            "bne.un"         => "Transfers control to a target instruction when two unsigned integer values or unordered float values are not equal.",
            "bne.un.s"       => "Transfers control to a target instruction (short form) when two unsigned integer values or unordered float values are not equal.",
            "box"            => "Converts a value type to an object reference (type O).",
            "br"             => "Unconditionally transfers control to a target instruction.",
            "br.s"           => "Unconditionally transfers control to a target instruction (short form).",
            "break"          => "Signals the Common Language Infrastructure (CLI) to inform the debugger that a break point has been tripped.",
            "brfalse"        => "Transfers control to a target instruction if <paramref name=\"value\" /> is false, a null reference (Nothing in Visual Basic), or zero.",
            "brfalse.s"      => "Transfers control to a target instruction if <paramref name=\"value\" /> is false, a null reference, or zero.",
            "brtrue"         => "Transfers control to a target instruction if <paramref name=\"value\" /> is true, not null, or non-zero.",
            "brtrue.s"       => "Transfers control to a target instruction (short form) if <paramref name=\"value\" /> is true, not null, or non-zero.",
            "call"           => "Calls the method indicated by the passed method descriptor.",
            "calli"          => "Calls the method indicated on the evaluation stack (as a pointer to an entry point) with arguments described by a calling convention.",
            "callvirt"       => "Calls a late-bound method on an object, pushing the return value onto the evaluation stack.",
            "castclass"      => "Attempts to cast an object passed by reference to the specified class.",
            "ceq"            => "Compares two values. If they are equal, the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
            "cgt"            => "Compares two values. If the first value is greater than the second, the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
            "cgt.un"         => "Compares two unsigned or unordered values. If the first value is greater than the second, the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
            "ckfinite"       => "Throws <see cref=\"T:System.ArithmeticException\" /> if value is not a finite number.",
            "clt"            => "Compares two values. If the first value is less than the second, the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
            "clt.un"         => "Compares the unsigned or unordered values <paramref name=\"value1\" /> and <paramref name=\"value2\" />. If <paramref name=\"value1\" /> is less than <paramref name=\"value2\" />, then the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
            "constrained."   => "Constrains the type on which a virtual method call is made.",
            "conv.i"         => "Converts the value on top of the evaluation stack to native int.",
            "conv.i1"        => "Converts the value on top of the evaluation stack to int8, then extends (pads) it to int32.",
            "conv.i2"        => "Converts the value on top of the evaluation stack to int16, then extends (pads) it to int32.",
            "conv.i4"        => "Converts the value on top of the evaluation stack to int32.",
            "conv.i8"        => "Converts the value on top of the evaluation stack to int64.",
            "conv.ovf.i"     => "Converts the signed value on top of the evaluation stack to signed native int, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i.un"  => "Converts the unsigned value on top of the evaluation stack to signed native int, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i1"    => "Converts the signed value on top of the evaluation stack to signed int8 and extends it to int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i1.un" => "Converts the unsigned value on top of the evaluation stack to signed int8 and extends it to int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i2"    => "Converts the signed value on top of the evaluation stack to signed int16 and extending it to int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i2.un" => "Converts the unsigned value on top of the evaluation stack to signed int16 and extends it to int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i4"    => "Converts the signed value on top of the evaluation stack to signed int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i4.un" => "Converts the unsigned value on top of the evaluation stack to signed int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i8"    => "Converts the signed value on top of the evaluation stack to signed int64, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.i8.un" => "Converts the unsigned value on top of the evaluation stack to signed int64, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u"     => "Converts the signed value on top of the evaluation stack to unsigned native int, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u.un"  => "Converts the unsigned value on top of the evaluation stack to unsigned native int, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u1"    => "Converts the signed value on top of the evaluation stack to unsigned int8 and extends it to int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u1.un" => "Converts the unsigned value on top of the evaluation stack to unsigned int8 and extends it to int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u2"    => "Converts the signed value on top of the evaluation stack to unsigned int16 and extends it to int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u2.un" => "Converts the unsigned value on top of the evaluation stack to unsigned int16 and extends it to int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u4"    => "Converts the signed value on top of the evaluation stack to unsigned int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u4.un" => "Converts the unsigned value on top of the evaluation stack to unsigned int32, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u8"    => "Converts the signed value on top of the evaluation stack to unsigned int64, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.ovf.u8.un" => "Converts the unsigned value on top of the evaluation stack to unsigned int64, throwing <see cref=\"T:System.OverflowException\" /> on overflow.",
            "conv.r.un"      => "Converts the unsigned integer value on top of the evaluation stack to float32.",
            "conv.r4"        => "Converts the value on top of the evaluation stack to float32.",
            "conv.r8"        => "Converts the value on top of the evaluation stack to float64.",
            "conv.u"         => "Converts the value on top of the evaluation stack to unsigned native int, and extends it to native int.",
            "conv.u1"        => "Converts the value on top of the evaluation stack to unsigned int8, and extends it to int32.",
            "conv.u2"        => "Converts the value on top of the evaluation stack to unsigned int16, and extends it to int32.",
            "conv.u4"        => "Converts the value on top of the evaluation stack to unsigned int32, and extends it to int32.",
            "conv.u8"        => "Converts the value on top of the evaluation stack to unsigned int64, and extends it to int64.",
            "cpblk"          => "Copies a specified number bytes from a source address to a destination address.",
            "cpobj"          => "Copies the value type located at the address of an object (type &amp;, * or native int) to the address of the destination object (type &amp;, * or native int).",
            "div"            => "Divides two values and pushes the result as a floating-point (type F) or quotient (type int32) onto the evaluation stack.",
            "div.un"         => "Divides two unsigned integer values and pushes the result (int32) onto the evaluation stack.",
            "dup"            => "Copies the current topmost value on the evaluation stack, and then pushes the copy onto the evaluation stack.",
            "endfilter"      => "Transfers control from the filter clause of an exception back to the Common Language Infrastructure (CLI) exception handler.",
            "endfinally"     => "Transfers control from the fault or finally clause of an exception block back to the Common Language Infrastructure (CLI) exception handler.",
            "initblk"        => "Initializes a specified block of memory at a specific address to a given size and initial value.",
            "initobj"        => "Initializes each field of the value type at a specified address to a null reference or a 0 of the appropriate primitive type.",
            "isinst"         => "Tests whether an object reference (type O) is an instance of a particular class.",
            "jmp"            => "Exits current method and jumps to specified method.",
            "ldarg"          => "Loads an argument (referenced by a specified index value) onto the stack.",
            "ldarg.0"        => "Loads the argument at index 0 onto the evaluation stack.",
            "ldarg.1"        => "Loads the argument at index 1 onto the evaluation stack.",
            "ldarg.2"        => "Loads the argument at index 2 onto the evaluation stack.",
            "ldarg.3"        => "Loads the argument at index 3 onto the evaluation stack.",
            "ldarg.s"        => "Loads the argument (referenced by a specified short form index) onto the evaluation stack.",
            "ldarga"         => "Load an argument address onto the evaluation stack.",
            "ldarga.s"       => "Load an argument address, in short form, onto the evaluation stack.",
            "ldc.i4"         => "Pushes a supplied value of type int32 onto the evaluation stack as an int32.",
            "ldc.i4.0"       => "Pushes the integer value of 0 onto the evaluation stack as an int32.",
            "ldc.i4.1"       => "Pushes the integer value of 1 onto the evaluation stack as an int32.",
            "ldc.i4.2"       => "Pushes the integer value of 2 onto the evaluation stack as an int32.",
            "ldc.i4.3"       => "Pushes the integer value of 3 onto the evaluation stack as an int32.",
            "ldc.i4.4"       => "Pushes the integer value of 4 onto the evaluation stack as an int32.",
            "ldc.i4.5"       => "Pushes the integer value of 5 onto the evaluation stack as an int32.",
            "ldc.i4.6"       => "Pushes the integer value of 6 onto the evaluation stack as an int32.",
            "ldc.i4.7"       => "Pushes the integer value of 7 onto the evaluation stack as an int32.",
            "ldc.i4.8"       => "Pushes the integer value of 8 onto the evaluation stack as an int32.",
            "ldc.i4.m1"      => "Pushes the integer value of -1 onto the evaluation stack as an int32.",
            "ldc.i4.s"       => "Pushes the supplied int8 value onto the evaluation stack as an int32, short form.",
            "ldc.i8"         => "Pushes a supplied value of type int64 onto the evaluation stack as an int64.",
            "ldc.r4"         => "Pushes a supplied value of type float32 onto the evaluation stack as type F (float).",
            "ldc.r8"         => "Pushes a supplied value of type float64 onto the evaluation stack as type F (float).",
            "ldelem"         => "Loads the element at a specified array index onto the top of the evaluation stack as the type specified in the instruction. ",
            "ldelem.i"       => "Loads the element with type native int at a specified array index onto the top of the evaluation stack as a native int.",
            "ldelem.i1"      => "Loads the element with type int8 at a specified array index onto the top of the evaluation stack as an int32.",
            "ldelem.i2"      => "Loads the element with type int16 at a specified array index onto the top of the evaluation stack as an int32.",
            "ldelem.i4"      => "Loads the element with type int32 at a specified array index onto the top of the evaluation stack as an int32.",
            "ldelem.i8"      => "Loads the element with type int64 at a specified array index onto the top of the evaluation stack as an int64.",
            "ldelem.r4"      => "Loads the element with type float32 at a specified array index onto the top of the evaluation stack as type F (float).",
            "ldelem.r8"      => "Loads the element with type float64 at a specified array index onto the top of the evaluation stack as type F (float).",
            "ldelem.ref"     => "Loads the element containing an object reference at a specified array index onto the top of the evaluation stack as type O (object reference).",
            "ldelem.u1"      => "Loads the element with type unsigned int8 at a specified array index onto the top of the evaluation stack as an int32.",
            "ldelem.u2"      => "Loads the element with type unsigned int16 at a specified array index onto the top of the evaluation stack as an int32.",
            "ldelem.u4"      => "Loads the element with type unsigned int32 at a specified array index onto the top of the evaluation stack as an int32.",
            "ldelema"        => "Loads the address of the array element at a specified array index onto the top of the evaluation stack as type &amp; (managed pointer).",
            "ldfld"          => "Finds the value of a field in the object whose reference is currently on the evaluation stack.",
            "ldflda"         => "Finds the address of a field in the object whose reference is currently on the evaluation stack.",
            "ldftn"          => "Pushes an unmanaged pointer (type native int) to the native code implementing a specific method onto the evaluation stack.",
            "ldind.i"        => "Loads a value of type native int as a native int onto the evaluation stack indirectly.",
            "ldind.i1"       => "Loads a value of type int8 as an int32 onto the evaluation stack indirectly.",
            "ldind.i2"       => "Loads a value of type int16 as an int32 onto the evaluation stack indirectly.",
            "ldind.i4"       => "Loads a value of type int32 as an int32 onto the evaluation stack indirectly.",
            "ldind.i8"       => "Loads a value of type int64 as an int64 onto the evaluation stack indirectly.",
            "ldind.r4"       => "Loads a value of type float32 as a type F (float) onto the evaluation stack indirectly.",
            "ldind.r8"       => "Loads a value of type float64 as a type F (float) onto the evaluation stack indirectly.",
            "ldind.ref"      => "Loads an object reference as a type O (object reference) onto the evaluation stack indirectly.",
            "ldind.u1"       => "Loads a value of type unsigned int8 as an int32 onto the evaluation stack indirectly.",
            "ldind.u2"       => "Loads a value of type unsigned int16 as an int32 onto the evaluation stack indirectly.",
            "ldind.u4"       => "Loads a value of type unsigned int32 as an int32 onto the evaluation stack indirectly.",
            "ldlen"          => "Pushes the number of elements of a zero-based, one-dimensional array onto the evaluation stack.",
            "ldloc"          => "Loads the local variable at a specific index onto the evaluation stack.",
            "ldloc.0"        => "Loads the local variable at index 0 onto the evaluation stack.",
            "ldloc.1"        => "Loads the local variable at index 1 onto the evaluation stack.",
            "ldloc.2"        => "Loads the local variable at index 2 onto the evaluation stack.",
            "ldloc.3"        => "Loads the local variable at index 3 onto the evaluation stack.",
            "ldloc.s"        => "Loads the local variable at a specific index onto the evaluation stack, short form.",
            "ldloca"         => "Loads the address of the local variable at a specific index onto the evaluation stack.",
            "ldloca.s"       => "Loads the address of the local variable at a specific index onto the evaluation stack, short form.",
            "ldnull"         => "Pushes a null reference (type O) onto the evaluation stack.",
            "ldobj"          => "Copies the value type object pointed to by an address to the top of the evaluation stack.",
            "ldsfld"         => "Pushes the value of a static field onto the evaluation stack.",
            "ldsflda"        => "Pushes the address of a static field onto the evaluation stack.",
            "ldstr"          => "Pushes a new object reference to a string literal stored in the metadata.",
            "ldtoken"        => "Converts a metadata token to its runtime representation, pushing it onto the evaluation stack.",
            "ldvirtftn"      => "Pushes an unmanaged pointer (type native int) to the native code implementing a particular virtual method associated with a specified object onto the evaluation stack.",
            "leave"          => "Exits a protected region of code, unconditionally transferring control to a specific target instruction.",
            "leave.s"        => "Exits a protected region of code, unconditionally transferring control to a target instruction (short form).",
            "localloc"       => "Allocates a certain number of bytes from the local dynamic memory pool and pushes the address (a transient pointer, type *) of the first allocated byte onto the evaluation stack.",
            "mkrefany"       => "Pushes a typed reference to an instance of a specific type onto the evaluation stack.",
            "mul"            => "Multiplies two values and pushes the result on the evaluation stack.",
            "mul.ovf"        => "Multiplies two integer values, performs an overflow check, and pushes the result onto the evaluation stack.",
            "mul.ovf.un"     => "Multiplies two unsigned integer values, performs an overflow check, and pushes the result onto the evaluation stack.",
            "neg"            => "Negates a value and pushes the result onto the evaluation stack.",
            "newarr"         => "Pushes an object reference to a new zero-based, one-dimensional array whose elements are of a specific type onto the evaluation stack.",
            "newobj"         => "Creates a new object or a new instance of a value type, pushing an object reference (type O) onto the evaluation stack.",
            "nop"            => "Fills space if opcodes are patched. No meaningful operation is performed although a processing cycle can be consumed.",
            "not"            => "Computes the bitwise complement of the integer value on top of the stack and pushes the result onto the evaluation stack as the same type.",
            "or"             => "Compute the bitwise complement of the two integer values on top of the stack and pushes the result onto the evaluation stack.",
            "pop"            => "Removes the value currently on top of the evaluation stack.",
            "prefix1"        => "This is a reserved instruction.",
            "prefix2"        => "This is a reserved instruction.",
            "prefix3"        => "This is a reserved instruction.",
            "prefix4"        => "This is a reserved instruction.",
            "prefix5"        => "This is a reserved instruction.",
            "prefix6"        => "This is a reserved instruction.",
            "prefix7"        => "This is a reserved instruction.",
            "prefixref"      => "This is a reserved instruction.",
            "readonly."      => "Specifies that the subsequent array address operation performs no type check at run time, and that it returns a managed pointer whose mutability is restricted.",
            "refanytype"     => "Retrieves the type token embedded in a typed reference.",
            "refanyval"      => "Retrieves the address (type &amp;) embedded in a typed reference.",
            "rem"            => "Divides two values and pushes the remainder onto the evaluation stack.",
            "rem.un"         => "Divides two unsigned values and pushes the remainder onto the evaluation stack.",
            "ret"            => "Returns from the current method, pushing a return value (if present) from the callee's evaluation stack onto the caller's evaluation stack.",
            "rethrow"        => "Rethrows the current exception.",
            "shl"            => "Shifts an integer value to the left (in zeroes) by a specified number of bits, pushing the result onto the evaluation stack.",
            "shr"            => "Shifts an integer value (in sign) to the right by a specified number of bits, pushing the result onto the evaluation stack.",
            "shr.un"         => "Shifts an unsigned integer value (in zeroes) to the right by a specified number of bits, pushing the result onto the evaluation stack.",
            "sizeof"         => "Pushes the size, in bytes, of a supplied value type onto the evaluation stack.",
            "starg"          => "Stores the value on top of the evaluation stack in the argument slot at a specified index.",
            "starg.s"        => "Stores the value on top of the evaluation stack in the argument slot at a specified index, short form.",
            "stelem"         => "Replaces the array element at a given index with the value on the evaluation stack, whose type is specified in the instruction.",
            "stelem.i"       => "Replaces the array element at a given index with the native int value on the evaluation stack.",
            "stelem.i1"      => "Replaces the array element at a given index with the int8 value on the evaluation stack.",
            "stelem.i2"      => "Replaces the array element at a given index with the int16 value on the evaluation stack.",
            "stelem.i4"      => "Replaces the array element at a given index with the int32 value on the evaluation stack.",
            "stelem.i8"      => "Replaces the array element at a given index with the int64 value on the evaluation stack.",
            "stelem.r4"      => "Replaces the array element at a given index with the float32 value on the evaluation stack.",
            "stelem.r8"      => "Replaces the array element at a given index with the float64 value on the evaluation stack.",
            "stelem.ref"     => "Replaces the array element at a given index with the object ref value (type O) on the evaluation stack.",
            "stfld"          => "Replaces the value stored in the field of an object reference or pointer with a new value.",
            "stind.i"        => "Stores a value of type native int at a supplied address.",
            "stind.i1"       => "Stores a value of type int8 at a supplied address.",
            "stind.i2"       => "Stores a value of type int16 at a supplied address.",
            "stind.i4"       => "Stores a value of type int32 at a supplied address.",
            "stind.i8"       => "Stores a value of type int64 at a supplied address.",
            "stind.r4"       => "Stores a value of type float32 at a supplied address.",
            "stind.r8"       => "Stores a value of type float64 at a supplied address.",
            "stind.ref"      => "Stores a object reference value at a supplied address.",
            "stloc"          => "Pops the current value from the top of the evaluation stack and stores it in a the local variable list at a specified index.",
            "stloc.0"        => "Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index 0.",
            "stloc.1"        => "Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index 1.",
            "stloc.2"        => "Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index 2.",
            "stloc.3"        => "Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index 3.",
            "stloc.s"        => "Pops the current value from the top of the evaluation stack and stores it in a the local variable list at <paramref name=\"index\" /> (short form).",
            "stobj"          => "Copies a value of a specified type from the evaluation stack into a supplied memory address.",
            "stsfld"         => "Replaces the value of a static field with a value from the evaluation stack.",
            "sub"            => "Subtracts one value from another and pushes the result onto the evaluation stack.",
            "sub.ovf"        => "Subtracts one integer value from another, performs an overflow check, and pushes the result onto the evaluation stack.",
            "sub.ovf.un"     => "Subtracts one unsigned integer value from another, performs an overflow check, and pushes the result onto the evaluation stack.",
            "switch"         => "Implements a jump table.",
            "tail."          => "Performs a postfixed method call instruction such that the current method's stack frame is removed before the actual call instruction is executed.",
            "throw"          => "Throws the exception object currently on the evaluation stack.",
            "unaligned."     => "Indicates that an address currently atop the evaluation stack might not be aligned to the natural size of the immediately following ldind, stind, ldfld, stfld, ldobj, stobj, initblk, or cpblk instruction.",
            "unbox"          => "Converts the boxed representation of a value type to its unboxed form.",
            "unbox.any"      => "Converts the boxed representation of a type specified in the instruction to its unboxed form. ",
            "volatile."      => "Specifies that an address currently atop the evaluation stack might be volatile, and the results of reading that location cannot be cached or that multiple stores to that location cannot be suppressed.",
            "xor"            => "Computes the bitwise XOR of the top two values on the evaluation stack, pushing the result onto the evaluation stack.",
            _                => null
        };

        private static string RegexReplace(this string s, string pattern, MatchEvaluator evaluator)
            => Regex.Replace(s, pattern, evaluator);
    }
}
