version: '{build}'
image: Visual Studio 2019
environment:
  marketplaceKey:
    secure: /V44/pvMDD3CZ/FJKsgY6FC+xR4Sa6jwsLEAtzYmfwA8v8Qvt4vhrPf2jYWI+4DAW3lL9eCTUxnUIsgkRzZwgw==
build_script:
- ps: ./build --no-logo
test_script:
- ps: ./build --target test --skip --no-logo
artifacts:
- path: ./src/VSExtension/bin/Release/Microscope.VSExtension.vsix
  name: Latest build
deploy_script:
- ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { ./build --target publish --publish-version $env:APPVEYOR_REPO_TAG_NAME --no-logo }
