// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microscope.VSExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageIdString = "b798b46c-201a-470c-9e3e-fa0abb23dfa7";
        public static Guid PackageId = new Guid(PackageIdString);

        public const string CmdSetIdString = "32872e4d-3d0e-4b26-9ef8-d3a90080429f";
        public static Guid CmdSetId = new Guid(CmdSetIdString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RefreshCommandId = 0x0100;
    }
}