// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microscope.VSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ede7ef0f-017b-4b33-b7b3-c7480d3cc712";
        public const string Name = "microscope";
        public const string Description = @"Provides a CodeLens to inspect the intermediate language instructions of a method.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Robert Hofmann";
        public const string Tags = "CodeLens, CIL, MSIL, intermediate language";
    }
}
